### ISSUE TITLE
Some browsers cannot write to cookie connect.sid

### ISSUE THREAD

**Issue by 156554395** [expressjs/session#470] opened 2017-06-19 02:48 UTC
My code:
```js
App.use (session ({)
Secret: cookieSecret,
Resave: true,
Rolling: true,
SaveUninitialized: false,
Cookie: {
MaxAge: 5 * 60 * 1000, //5 minutes timeout
HttpOnly: true
}
}))
```

**Comment by 156554395** [comment] 2017-06-19 07:08
Using the following code in routing, the result is object:
console.log(req.signedCookies)
results:
{}

**Comment by 156554395** [comment] 2017-06-19 07:52
The problem occurs with this version of iPhone
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X)

**Comment by joewagner** [comment] 2017-06-19 14:53
Aside from some syntax errors in your code snippet, I don't see anything wrong.  Can you please provide 

1. The exact version of this module
2. The exact version of Node.js
3. The exact versions of all other modules needs to reproduce.
4. Full, complete source code we can copy and paste into a file and run.
5. Full, complete instructions on how to reproduce.

**Comment by 156554395** [comment] 2017-06-20 01:43
1、 version 
"dependencies": {
    "async": "^2.1.4",
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "ejs": "^2.5.2",
    "express": "~4.13.1",
    "glob": "^7.1.1",
    "morgan": "~1.6.1",
    "pinyin": "^2.8.0",
    "request": "^2.79.0",
    "serve-favicon": "~2.3.0",
    "express-http-proxy": "^0.10.1",
    "node-uuid": "^1.4.7",
    "excel-export": "^0.5.1",
    "express-session": "^1.14.2"
  }
2、version of Node.js
   v6.10.1

3、app.js
var cookieSecret='demo',
      login = require('./routes/login');
app.use(cookieParser(cookieSecret));
app.use(session({
    secret: cookieSecret,
    name: 'session_' + cookieSecret,
    resave: true,
    rolling: true,
    saveUninitialized: false,
    cookie: {
        maxAge: 5 * 60 * 1000,
        httpOnly: true
    }
}))
app.use('/login', login);
4、login.js
router.get('/test',function (req, res) {
    var sessions=req.session;
    sessions.username='testUser';
    console.log(req.signedCookies);
    res.json({
        singedCookies:req.signedCookies
    })
})

5、versions of iphone
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 MicroMessenger/6.5.8 NetType/WIFI Language/zh_CN

in this iphnoe, signedCookies is {};

**Comment by joewagner** [comment] 2017-06-20 16:35
The above is **not** a working example, but regardless...
1. signedCookies is an internal back compatible key and isn't guaranteed to be available.  Try `req.headers.cookie`
2. This module has no control over the browser's ability to write a cookie

**Comment by dougwilson** [comment] 2017-07-19 03:08
Closing since there hasn't been a response.

**Closed by dougwilson** 2017-07-19 03:08 UTC
