### ISSUE TITLE
Support "Forwarded" header as an alternative to "X-Forwarded-Proto"

### ISSUE THREAD

**Issue by nmalyschkin** [expressjs/session#886] opened 2022-04-22 09:10 UTC
### problem
Unfortunately AWS API Gateway is using the less standard header [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) when proxying requests.
This looks like this:
```
forwarded: by=1.2.3.4;for=5.6.7.8;host=my.example.com;proto=https
via: HTTP/1.1 AmazonAPIGateway
```

### solution
It would be great if we could support this header as a fallback when `X-Forwarded-Proto` is not present.

### solution alternative
`issecure` can be overwritten or extended with a function passed through options.

### security considerations
An external request might define the forward header to simulate as if it had been proxied.
Like the `X-Forwarded-Proto`, `Forwarded` is a forbidden request header and should not be set by browser and be deleted by proxies.

**Comment by dougwilson** [comment] 2022-04-22 13:02
Duplicate of #879

**Closed by dougwilson** 2022-04-22 13:02 UTC
