### ISSUE TITLE
Multiple session configurations getting wrong cookie path

### ISSUE THREAD

**Issue by mschipperheyn** [expressjs/session#613] opened 2018-09-21 22:23 UTC
Hi,

I'm running multiple session configurations: one for `/account` and one for `/admin`.

I'm seeing an issue in my test environment where I'm getting the wrong cookie path back.

``` 
import session from 'express-session';
import redisSession from 'connect-redis';
import redisClient from '../';
import config from '../../../../config';

const secret = config(`server.${process.env.NODE_ENV}.sessionHash`);
const secureCookie = config(`server.${process.env.NODE_ENV}.secureCookie`);

const RedisStore = redisSession(session);

const redisSessionMiddleWare = (app, pathArray) => {
  const store = new RedisStore({
    client: redisClient,
    checkExpirationInterval: 15 * 60 * 1000,
    expiration: 24 * 90 * 60 * 60 * 1000
  });

  pathArray.forEach(path => {
    app.use(
      path,
      session({
        name: `connect.${path.slice(1)}.sid`,
        secret,
        store,
        saveUninitialized: false,
        resave: false, 
        proxy: true,
        maxAge: null,
        cookie: {
          path,
          expires: false,
          secure: secureCookie,
          httpOnly: true
        }
      })
    );
  });
};

export default redisSessionMiddleWare;
```
I call this function with array `['/account','/admin']`
I use two passport instances to separate these two session configurations.

What I see coming back in a test where I login the user against the `/account` configuration

```
{ 'x-powered-by': 'Express',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '121',
      etag: 'W/"79-D8DXGRyLafctjYYqUTCdTzPheS8"',
      'set-cookie': 
       [ 'connect.account.sid=s%3AewWpmjvMZq-sXEtOESxXJfvohrJT62q6.zb9Wpbi2orm9CJf3XyWdyhT28M5Uo2Q2hJ25ARacqOI; Path=/admin; HttpOnly' ],
      connection: 'close' }
```

Note that the Path = different from the session key. Per the code, I would expect the Path to be `/account`

That seems odd, given that this configuration *should*  setup the `connect.account.sid` together with the `/account` path. It seems like it takes the correct session name but the last cookie path in the array (`/admin`)

Is there any obvious way where the cookie path will not be what was passed in the configuration?

**Comment by dougwilson** [comment] 2018-09-22 23:30
The issue is that the same `store` is being passed to both middleware instances and this middleware will actually add a `.generate` method to your passed-in store object. The second call into the middleware replaces the `.generate` method from the first call with the second. The `.generate` method (accessed as `store.generate(req)`) generates a new session, and since part of the session data is the cookie, that cookie data is embedded into the generate method.

**Comment by dougwilson** [comment] 2018-09-22 23:31
It is a duplicate of #521

**Closed by dougwilson** 2018-09-22 23:31 UTC
Labels: investigate
