### ISSUE TITLE
session not saving in safari

### ISSUE THREAD

**Issue by olinations** [expressjs/session#638] opened 2019-02-27 23:23 UTC
When I get user to login, the session is created storing userId. I console log out and it is correct. The login function then returns res.json( 'some data' ). Then the frontend calls another api endpoint, which checks the session for the userid but it does not find it!!! The odd thing is that this works fine in Chrome but does not work in Safari. I have researched like crazy and implemented maybe hundreds of different fixes, none work. I am beginning to lose my mind. Please help!

In my fetch calls from frontend I am setting, credentials: 'include' 

I have https site. 

This is my session code. Please let me know if there is anything else you need to analyze this situation.

`app.use(
  session({
    store,
    name: process.env.SESSION_NAME,
    saveUninitialized: false,
    resave: false,
    secret: 'aBdi((90Lk',
    cookie: {
      maxAge: 1000 * 60 * 60 * 24 * 7, 
      sameSite: false,
      secure: true
    }
  })
)`

**Comment by dougwilson** [comment] 2019-04-24 19:45
Very strange. Duplicate of #610 ?

**Closed by dougwilson** 2019-04-24 19:45 UTC

**Comment by alexpapworth** [comment] 2022-05-30 20:43
#610 appears to have been deleted?
