### ISSUE TITLE
Enable secure cookies over localhost

### ISSUE THREAD

**Issue by thegoldgoat** [expressjs/session#857] opened 2021-12-22 12:19 UTC
I think it is reasonable to enable secure cookies on localhost, since browsers accepts them.

This simplifies development and avoid developers confusion, since now cookies are suppressed silently.

What I propose is updating isSecure:

https://github.com/expressjs/session/blob/0048bcac451ad867299d404aca94c79cc8bc751d/index.js#L623

And add something like this:

```js
if (req.connection.remoteAddress === '127.0.0.1' ||
    req.connection.remoteAddress === '::ffff:127.0.0.1'
) {
    return true;
}
```

I am opening a PR in a moment

Also see #837

**Comment by dougwilson** [comment] 2021-12-24 08:21
Hello, and thanks for opening this issue. It seems to be a duplicate of #837 though. I can re-open if there is elaboration on how it is not a duplicate, though.

**Closed by dougwilson** 2021-12-24 08:21 UTC
Labels: duplicate
