### ISSUE TITLE
Cookie with 2 month maxAge not being parsed for session lookup

### ISSUE THREAD

**Issue by dargue3** [expressjs/session#548] opened 2018-01-27 01:24 UTC
I had the following code which worked well for the last few weeks of development.
```
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(cookieParser(process.env.SESSION_SECRET));
app.use(compression());
app.use(session({
  resave: false,
  saveUninitialized: false,
  secret: process.env.SESSION_SECRET,
  cookie: { maxAge: 1000 * 3600 * 24 * 30 * 2 }, // 2 months (ms)
  store: new MemcachedStore({ hosts: process.env.MEMCACHE_URL.split(',') }),
}));
```

Without updating any packages, this stopped working this morning when I came to work. Every request was generating a new session (despite `connect.sid` cookie definitely being set in `req.cookies`).

Removing the `cookie` option fixes the problem. If I set `cookie: { expires: new Date('<tomorrow>') }`, this fixes the problem, if I put the expiration date a year into the future, it breaks again.

What changed recently that could have caused this? An update with memcache? Is there a max expiration on the cookie? Any insight would be great.

**Comment by dougwilson** [comment] 2018-01-27 01:27
I'm not aware that anything has changed recently. The last time this module was published was 4 months ago. I have no idea about memcache as I don't use it myself.

If you can provide all the following I can try to debug through the issue with you:

1. The version of Node.js
2. The version of this module and all other modules you're using
3. Complete code I can simply copy-and-paste to run without modification
4. Instructions on what to setup to get the server running
5. Instructions for how to reproduce the issue (first open browser to ... then click ... etc)

Looking forward for this information to help you out!

**Comment by dargue3** [comment] 2018-02-27 01:03
@cynicaloptimist that'd be great if you could do that, at the moment my fix is just to have the session end when the browser is closed.

**Comment by dougwilson** [comment] 2018-02-27 01:32
I agree, @cynicaloptimist . I don't see anything wrong in that diff. Very similar to what I do, in fact (use moment.js to calculate).

**Comment by cynicaloptimist** [comment] 2018-02-27 02:27
My issue went away when I stopped setting the `secure` flag. I suspect I was using it wrong, but I don't think I encountered this issue.

**Comment by dougwilson** [comment] 2018-03-09 13:28
Closing since I never got the information from https://github.com/expressjs/session/issues/548#issuecomment-360948400

**Closed by dougwilson** 2018-03-09 13:28 UTC
Labels: awaiting more info
