### ISSUE TITLE
Cookie-parser and version > 1.5

### ISSUE THREAD

**Issue by BobBatard** [expressjs/session#246] opened 2015-12-16 16:55 UTC
Hi,

this is not really an issue, but we would like to have your opinion on this.
Your doc is saying : 
"Note Since version 1.5.0, the cookie-parser middleware no longer needs to be used for this module to work. This module now directly reads and writes cookies on req/res. Using cookie-parser may result in issues if the secret is not the same between this module and cookie-parser."

This is exactly the situation we were unknowingly in when we experienced a really strange bug : 
  - A logged user was browsing our website
  - A new user went on our site from a different computer, and he was attributed the logged user session !

Is it one of the issue possibly created by using cookie-parser and a version > 1.5.0 with a different secret ?

**Comment by dougwilson** [comment] 2015-12-16 16:58
Hi @BobBatard , I think your question got cut off, so I'm not surer what your question is.

**Comment by BobBatard** [comment] 2015-12-16 17:02
I did a bad manipulation and I have now edited my original question ! Thanks for your reactivity !

**Comment by dougwilson** [comment] 2015-12-16 17:04
> Is it one of the issue possibly created by using cookie-parser and a version > 1.5.0 with a different secret ?

I'm not sure. I've never heard of this issue before. I doubt it has anything to do with `cookie-parser`, as if you have the wrong secret between the two, what would happen is just the cookie won't decode and it'll simply create a new session.

In order to understand what's going on, I'd probably have to see it in action, unless you're willing to debug the situation and provide an explanation/fix. In order for us to look into this, we'd need full source code, environment versions, and steps to reproduce the issue.

**Comment by BobBatard** [comment] 2015-12-16 17:20
We're still investigating on our side, it maybe has nothing to do with express.
We're not even able to reproduce the bug right now, so we have a long way to find its origin !

Right now the only other thing we can think of is if the id generated in the cookies with uid-safe was somehow the same for 2 unrelated users, which seems highly unlikely, if even possible.

Do you think it could happen ?

**Comment by gabeio** [comment] 2015-12-16 19:24
@BobBatard do you by chance have a custom generateId function? if you have the threshold too low you may end up having users getting other user's sessions...

**Comment by BobBatard** [comment] 2015-12-16 19:54
Nope, we're using the default function.
This is our code if it can be of any help : 
```javascript
var session = require('express-session')
  , store = require('connect-mongo')({ session: session })

app.use(require('cookie-parser')())
app.use(session({ 
    secret: secret 
  , key: key
  , cookie: { maxAge: (60000 * 60) * ( 24 * 5 ) } // 5day
  , store: new store({ url: config.store })
  , resave: false
  , saveUninitialized: false
}))
```

**Comment by dougwilson** [comment] 2016-01-10 18:42
Hi @BobBatard , I'm going to close this for now as it has almost been a month since the last activity. I'm not sure. I've never heard of this issue before. I doubt it has anything to do with `cookie-parser`, as if you have the wrong secret between the two, what would happen is just the cookie won't decode and it'll simply create a new session.

In order to understand what's going on, I'd probably have to see it in action, unless you're willing to debug the situation and provide an explanation/fix. In order for us to look into this, we'd need full source code, environment versions, and steps to reproduce the issue.

**Closed by dougwilson** 2016-01-10 18:42 UTC

**Comment by BobBatard** [comment] 2016-01-11 11:41
Hi doug, no problem, I don't think it was related to cookie-parser neither, but we weren't able to understand the bug or even reproduce it.

Thanks for your help anyway !
