### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by davepreston** [expressjs/session#699] opened 2019-10-09 20:34 UTC
Are there plans to release this to npm soon? I'm hoping the change to support SameSite=None will be in an official release (the code is already done the current release was 11 commits ago).

btw, thanks for all you do!

**Comment by dougwilson** [comment] 2019-10-09 20:35
duplicate of #696 . I'll post an update in there so it's together with the rest.

**Closed by dougwilson** 2019-10-09 20:35 UTC
