### ISSUE TITLE
Race condition when using req.session.save() in trying to redirect

### ISSUE THREAD

**Issue by mjquito** [expressjs/session#526] opened 2017-11-25 08:40 UTC
I'm experiencing issue [#74](https://github.com/expressjs/session/issues/74) that was closed. There are also similar issues reported in stackoverflow. 

Problem: Race condition when using `req.session.save()` 

Explanation: 
```
...
router.get('/logout', function(req, res, next){
    req.logout();
    res.redirect('/')
});
...
```
I'm trying to do a successful logout. I first call `req.logout()` to update the `req.session` and then I call `res.redirect('/')` to have express-session **update** the session to a file. I'm using the store session-file-store. The problem lies when `res.redirect('/'` calls `res.end()` inside the `./express-session/indes.js`

```
res.end(){
...
if (shouldSave(req)) {
        req.session.save(function onsave(err) {
          if (err) {
            defer(next, err);
          }
          writeend();
        });
        return writetop();
      } else if (storeImplementsTouch && shouldTouch(req)) {
...
```
`req.session.save` gets run asynchronously, which then immediately the redirects happens which loads a session, but the `req.session.save` **hasn't finished yet updating the file!** which then the old state of the session gets loaded and then the `req.session.save` finishes, but its too late:( 

```
...
"express": "4.16.2"
 "express-session": "1.15.6"
"session-file-store": "1.1.2"
...
app.use(session({
  store: new FileStore(),
  secret: 'keyboard mouse',
  resave: false,
  saveUninitialized: false
}));
...
```

I hope this makes sense. I tried the workaround offered in [#74](https://github.com/expressjs/session/issues/74) to call `res.session.save` before the redirect **BUT** then I end up calling the res.session.save twice! which [#74](https://github.com/expressjs/session/issues/74) supposedly should have fixed it.

Other similar issues
#309

**Comment by dougwilson** [comment] 2017-11-25 14:45
This is a known issue. Either call req.session.save in your code and put res.redirect in the callback to that or make a pull request with a solution. No one (even myself) has been able to make a workable patch yet.

**Comment by dougwilson** [comment] 2017-11-25 14:47
Closing as duplicate of #360 (let me know if you think this is not a duplicate and why and I can reopen).

**Closed by dougwilson** 2017-11-25 14:47 UTC

**Comment by mjquito** [comment] 2017-11-25 16:20
Thank you @dougwilson for the prompt response. Yes, same issue. This is a great library but I'm a bit in shock this problem exists in a library that is heavily used for other libs and apps.

**Comment by dougwilson** [comment] 2018-03-01 19:43
Yea, I would like to fix it, but not certain how. Any thoughts on it would be much appreciated!

**Comment by abcd-ca** [comment] 2022-09-22 02:49
Seems there are two options for a fix after experimenting and reading different github issues:

1. `req.session.save(err => _<handle error or res.redirect>_)` Should be ready by the time the callback is called
2. Get the front-end to do the redirect```
    res.set('Content-Type', 'text/html')
    res.send(
        Buffer.from(
             '<html lang="en"><head><meta http-equiv="refresh" content="0; url=/dashboard"><title>Insightfull</title></head><body>Loading...</body></html>'
        )
    )
     ```
Option 1 seems to work for me and be less kludgy. I did spend a couple hours scratching my head though why it stopped working in a modified environment. Turns out I was serving my Express app locally without SSL but had this set on my session store's options param: `sessionOptions.cookie.secure = true`. That was enough to prevent my custom session data from persisting in the session but I got no errors in the console. I suppose if one were to create a PR around this it would be to compare the request protocol with the session store `secure` option. I don't think I'll have time to do it, sorry.

Leaving this here in case it helps someone. 

Thanks for the library, it's actually really great!
