### ISSUE TITLE
avoid req.session being undefined even if !storeReady

### ISSUE THREAD

**Issue by LoneRifle** [expressjs/session#762] opened 2020-06-26 05:24 UTC
Our project currently uses express-session and cookie-session with its corresponding @DefinitelyTyped definitions. Recent updates to the latter have revealed that `req.session` as set by the two middlewares can take on slightly different types, as follows:

- cookie-session would set the property to be either:
  - an object on deserialization or creation, or;
  - `null` when set by a controller to [destroy the session](https://github.com/expressjs/cookie-session#destroying-a-session).

- express-session would set the property to be either:
  - an object on deserialization or creation;
  - `null` when set by a controller to [destroy the session](https://github.com/expressjs/session#unset), or; 
  - `undefined`, when the session store is not available.

It is the lattermost state that results in express-session type definitions that are incompatible with cookie-session. 

We hence propose that when the session store is unavailable, `req.session` is set to `null`, for the following reasons:

- Consistency with the shape of the property set by cookie-session;
- Largely backward compatible with code that checks for `req.session` truthiness to see if a session has been set;
- Retention of semantics regarding session destruction, where `req.sessionID` is non-null while `req.session` is null, since if the store is not available `req.sessionID` will not be populated anyway.

I am open to other approaches we can take to somehow bring cookie-session and express-session in-line, though I will note that discussions amongst TypeScript users have suggested that they generally expect `req.session` to be non-optional (ie, never `undefined`)

**Comment by dougwilson** [comment] 2020-06-26 05:32
> Largely backward compatible with code that checks for req.session truthiness to see if a session has been set;

Unfortunately it is not _actually_ backwards compatible, so it cannot be changed in the 1.x series. Yes, it works for those who check truthiness, but as it has always been undefined for all of the project's existence, and many linters telling users to use ===, it is highly likely users are using === undefined checks.

> I am open to other approaches we can take to somehow bring cookie-session and express-session in-line,

I'm not sure this project's issue tracker is the proper forum for such a discussion. Middlewares not by no means required to be compatible with each other like this, especially since they noth use the same property a single express app is unlikely to actually be able to use both at the same time.

> Though I will note that discussions amongst TypeScript users have suggested that they generally expect req.session to be non-optional (ie, never undefined)

This is not a typescript project, and we work to adhere to javascript principals and design patterns.

Ultimately I think overall this is really a duplicate of #4

**Closed by dougwilson** 2020-06-26 05:32 UTC
