### ISSUE TITLE
Feature request: Renew session id

### ISSUE THREAD

**Issue by wdetac** [expressjs/session#560] opened 2018-03-08 04:09 UTC
My goal is to change session id but make every other remain unchanged.
I think session.regenerate() will be useful. But it will destroy and re-create the session instance.
```
req.session.regenerate(function(err) {
    // will have a new session here
})
```
Can we have something like that?
```
req.session.regenerate(preserveData = false, function(err) {
    // will have a new session here
    // if preserveData set to true, preserve session data
})
```

**Comment by dougwilson** [comment] 2018-03-08 04:25
Definately something that has been on the docket, I believe. Duplicate of #425 I think. If you don't think this is a duplicate of that issue, I may be misunderstanding the feature request, I apologise!

**Closed by dougwilson** 2018-03-08 04:25 UTC

**Comment by wdetac** [comment] 2018-03-08 04:28
That one exactly what I mean, I missed that sorry.
