### ISSUE TITLE
Session cookie name is invalid in PHP

### ISSUE THREAD

**Issue by IngwiePhoenix** [expressjs/session#203] opened 2015-08-30 04:47 UTC
This is what happens:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ cat sess.php
<?php session_start(); print_r($_COOKIE); print_r($_SESSION);
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ curl -c c.jar -v http://localhost:8080/sess.php
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /sess.php HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-type: text/plain
< X-Meep: o.o
* Added cookie PHPSESSID="s%3A3Of-UMl7Guv3v4yfpPch8CwD6NVGp36k.y%2FgqnX8SUBnNB2uTFPBB17eVWeBO8zn9ntEq0anBzjw" for domain localhost, path /, expire 0
< set-cookie: PHPSESSID=s%3A3Of-UMl7Guv3v4yfpPch8CwD6NVGp36k.y%2FgqnX8SUBnNB2uTFPBB17eVWeBO8zn9ntEq0anBzjw; Path=/; HttpOnly
< X-Response-Time: 131.484ms
< Vary: Accept-Encoding
< Date: Sun, 30 Aug 2015 04:44:35 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
Array ( ) Array ( )
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ curl -b c.jar -v http://localhost:8080/sess.php
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /sess.php HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:8080
> Accept: */*
> Cookie: PHPSESSID=s%3A3Of-UMl7Guv3v4yfpPch8CwD6NVGp36k.y%2FgqnX8SUBnNB2uTFPBB17eVWeBO8zn9ntEq0anBzjw
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-type: text/plain
< X-Meep: o.o
< X-Response-Time: 99.574ms
< Vary: Accept-Encoding
< Date: Sun, 30 Aug 2015 04:44:46 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /Users/Ingwie/Work/BIRD3/sess.php on line 1 Call Stack: 0.0003 245896 1. {main}() /Users/Ingwie/Work/BIRD3/php-lib/executor.php:0 0.0046 893120 2. require_once('/Users/Ingwie/Work/BIRD3/sess.php') /Users/Ingwie/Work/BIRD3/php-lib/executor.php:69 0.0046 893168 3. session_start() /Users/Ingwie/Work/BIRD3/sess.php:1 Array ( [PHPSESSID] => s:3Of-UMl7Guv3v4yfpPch8CwD6NVGp36k.y/gqnX8SUBnNB2uTFPBB17eVWeBO8zn9ntEq0anBzjw ) Array ( )
```

Basically, the "s:" prefix is causing PHP to freak out when trying to re-generate the session. Trying to set `secret` to false throws me the error that it is required.

Could you add a workaround here? Thanks!

**Comment by ns-cweber** [comment] 2017-03-09 19:18
This is invalid to the Go HTTP stack as well: https://play.golang.org/p/Kq9Wqk3XLu

According to the [Mozilla documentation on the "Set-Cookie" header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie): `A <cookie-name> can be anything but control characters (CTLs) or spaces and tabs. It also must not contain a separator character like the following: ( ) < > @ , ; : \ " /  [ ] ? = { }.`

**Comment by dougwilson** [comment] 2017-03-09 19:25
I'm not sure I'm following. The default cookie name is `connect.sid` (https://github.com/expressjs/session#name), which doesn't contain any of the chars listed on that MDN article, confirmed with the RFC 6265 which defines the `Set-Cookie` spec (the cookie name can be anything of `token` defined in RFC 2616 according to the spec). If you need a different one, just change the `name` option.

**Comment by dougwilson** [comment] 2017-03-09 19:28
Apparently the comment I replied to has been deleted... ? @ns-cweber

**Comment by ns-cweber** [comment] 2017-03-14 18:46
@dougwilson Yeah, you're fast. I misunderstood the cookie being discussed and realized my error shortly after posting and deleted my post. I didn't think anyone would have seen it in that time. Sorry for the confusion.

**Comment by dougwilson** [comment] 2018-03-15 01:20
Closing because I'm not clear on the ask and there has never been any follow up.

**Closed by dougwilson** 2018-03-15 01:20 UTC
