### ISSUE TITLE
After adding cluster, my sessionID always change

### ISSUE THREAD

**Issue by CatWithWings** [expressjs/session#554] opened 2018-02-12 03:05 UTC
I have a Nodejs application and I'm using cluster, express-session and MongoStore.
When the user logged in success, I'll put some info into the session ,and the session will store in the mongodb. But when the request is handled by other proccess, the session.id will change, so I can't query the data by the sessionID. Why did this happen?

This is my config:

```
app.use(session({
     secret: SESSIONSECRET,
     store: new MongoStore({ mongooseConnection: db, stringify: false}),
     name: 'sessionUserId',
     saveUninitialized: false,
     resave: false,
     rolling: true,
     genid: function(req) {
         return uuidv1() // use UUIDs for session IDs
    },
    cookie: {
         secure: false,
         maxAge: 28800000
    }
}));
```

**Comment by dougwilson** [comment] 2018-02-16 16:57
Hi @CatWithWings that is strange indeed. I have never seen that happen and don't know what could be wrong. If you know a fix, please feel free to make a pull request 👍 otherwise, if you can help us debug it by providing the following information:

1. Version of Node.js
2. Version of this and all other used modules
3. Complete server source code needed to reproduce the issue. It doesn't have to be your real code, just code we can copy and paste and run to reproduce. Remove the unnecessary parts, for example.
4. Instructions for how to get it all setup if you're not using the built-in memory store. This is because if you're using a database, it's possible the issue is some config there, so getting it setup on our end the same way you have is ideal.
5. Instructions for how to then reproduce the issue. Open web browser click here, click there, etc. If you script this out that works too.

I look forward to being able to get this resolved 👍

**Comment by dougwilson** [comment] 2018-03-09 13:27
Closing since I never heard back.

**Closed by dougwilson** 2018-03-09 13:27 UTC
Labels: awaiting more info
