### ISSUE TITLE
Intermittently sess.cookie is undefined ("Cannot read property 'expires' of undefined")

### ISSUE THREAD

**Issue by chrisiona** [expressjs/session#551] opened 2018-02-03 02:17 UTC
Hi folks,

I have an express app using `express-session`, backed with memcache (ElastiCache).

However, I intermittently find that all sessions are being "forgotten", which I traced down to `sess.cookie` being `undefined` (as below).

Using Memcache as the session store is definitely working (eg when I reboot the web server, session state is maintained), and I've tried both `connect-memjs` and `connect-memcache` libs, with similar results.

I can replicate the issue by refreshing my app in browser, using multiple browsers to simulate multiple sessions.  I found it occurs with 2-5 minutes (or 50 – 250 refreshes).  This happens with either memcache libs.

When it happens, all existing sessions are given a new session ID at the same time, so maybe a race condition?

* Any thoughts on why `sess.cookie` wouldn't be set?
* Is there a "better" memcache lib to be using?

**Node version**
`v8.9.4`

**Packages**
```
    "connect-memcached": "^0.2.0",
    "connect-memjs": "^0.2.1",
    "express": "~4.15.2",
    "express-session": "^1.15.6",
```

**Log Output**
```
<path>/master/node_modules/express-session/session/store.js:87
  var expires = sess.cookie.expires
                            ^

TypeError: Cannot read property 'expires' of undefined
    at MemcachedStore.Store.createSession (<path>/master/node_modules/express-session/session/store.js:87:29)
    at <path>/master/node_modules/express-session/index.js:478:15
    at <path>/master/node_modules/connect-memjs/lib/connect-memjs.js:139:11
    at <path>/master/node_modules/memjs/lib/memjs/memjs.js:139:23
    at responseHandler (<path>/master/node_modules/memjs/lib/memjs/memjs.js:770:21)
    at Server.respond (<path>/master/node_modules/memjs/lib/memjs/server.js:45:3)
    at Server.responseHandler (<path>/master/node_modules/memjs/lib/memjs/server.js:106:12)
    at Socket.<anonymous> (<path>/master/node_modules/memjs/lib/memjs/server.js:140:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #3
```

**Session Configuration**

```
{
  secret: 'xxxxxxxx'
  resave: false,  // Tried both true and false
  name: '<my unique id>',
  saveUninitialized: false,  // Tried both true and false
  cookie: { 
      maxAge: (4*60*60*1000), // 4 hours
      secure: true 
  },
  store: {
      servers: [
          '<elasticache memcache instance>:<port>'
      ],
      secret: 'xxxxxxxx'
  }
}
```

Thanks

**Comment by chrisiona** [comment] 2018-02-04 22:21
Hmm, it is possible this is related to having a secret that is too long (>140chars).

Will try with 16, 32, 64 and 96 chars and report back findings

**Comment by dougwilson** [comment] 2018-02-16 17:02
Hi @chrisiona very strange. I wouldn't think the length of the secret would matter, because it's just a function for the HMAC, which will always end up being the same length in the end (since the result is a fixed-length hash). I wonder if I can get this code up and running to debug through it to figure out what is happening. Would you be able to provide the following?

1. Complete server code that I can just copy and paste and run that has the issue? It doesn't need to be your real code, just some code that works after a copy and paste.
2. Instructions on how to reproduce with that code, probably "open browser to .... click ... etc."

Thanks!

**Comment by dougwilson** [comment] 2018-03-09 13:27
Closing since I never heard back.

**Closed by dougwilson** 2018-03-09 13:27 UTC
Labels: awaiting more info

**Comment by chrisiona** [comment] 2018-04-13 13:59
Hi @dougwilson — Haven't been able to replicate since.  Maybe ElastiCache was having issues at the time...  Thanks anyway

**Comment by Teivaz** [comment] 2018-12-22 22:40
I had similar behavior when the second argument of the `options.store.set` function was ignored.
I have used `connect-mongodb-session`. This was **not an issue** with any of these two libraries - I have wrapped the function badly so the database had following record:

```
> db.usersession.find()
{ "_id" : "97fa4768-36b1-4672-0540-63da47e355d8", "expires" : ISODate("2019-01-05T21:54:06.334Z"), "session" : {  } }
```

Which was crashing the service and I had to clean up the database.

For reference here is a healthy record:
```
{ "_id" : "93a1f25f-2fba-47fe-0d36-a4002f16eda8", "session" : { "cookie" : { "originalMaxAge" : null, "expires" : null, "secure" : true, "httpOnly" : true, "domain" : null, "path" : "/", "sameSite" : null }, "passport" : { "user" : "ae288f3f-08aa-4b65-18a1-10556938e094" } }, "expires" : ISODate("2018-12-28T20:49:37.472Z") }
```

**Comment by JBaczuk** [comment] 2022-03-04 17:04
For me, this error was thrown because the session format was switched from string to object.
