### ISSUE TITLE
Users ending up in each others'  sessions w/SPA and API on separate subdomains after AWS migration

### ISSUE THREAD

**Issue by rerorr19** [expressjs/session#780] opened 2020-08-30 18:35 UTC
I've split a SPA React client and the API into two different subdomains in the context of a migration from Heroku to AWS. The session handling was previously working without a hitch. I am continuing to use Redis as a distributed key store for the Express-Session id, and there is adequate memory, so it should be unique. I am using CloudFront with an ELB load balancer but not CloudFront session handling and there is no CDN caching enabled. With multiple instances of the API server running in a cluster and concurrent requests, **users are sporadically ending up in other users' sessions**. The issue can be reproduced occasionally after repeatedly experimenting with refreshing in the browser and clearing the browser cache/local storage. It's not clear, but it seems to be possibly repeated users from a small pool which recur. I noticed that the 
connect.sid appears in the cookie in the request to the API, not the front end, but that shouldn't be an issue. In the majority of cases the session is functioning normally The issue cannot be reproduced on Heroku or with one server container instance running on AWS. Has anyone experienced an issue similar to this?

**Comment by davidmashe** [comment] 2020-09-01 00:34
Hard for us to give any further input unless you can demonstrate this is a defect in `session`.

**Comment by rerorr19** [comment] 2020-09-02 18:01
We don't suspect that it's a defect in session necessarily, but I was asked to inquire about any known session issues related to having the SPA and API on different subdomains. So far we could only reproduce the issue in our AWS environment with the two subdomains  and are not sure why users would sporadically end up in each other's sessions. I know it's not much to work with.

**Comment by dougwilson** [comment] 2020-09-02 18:35
Hi @rerorr19 though we're not sure what your issue could be, the only real suspect here is some kind of AWS configuration. I can say from experience, the only time this exact issue has come up where a user followed up with what their root case was, it was that their reverse proxy was performing caching of back-end responses, typically just on static assets. Since their Express app was configured to send `Set-Cookie` even on static assets, that header was also cached, so users would end up getting that cookie from another user set in their browser, taking on that user's identity. They typically seem to fix it by configuring their cache to drop any `set-cookie` response headers.

**Comment by jikyu** [comment] 2020-10-30 08:16
We ran into this exact issue recently when we migrated our SPA React / Next.js app to a domain different from the API server. Our AWS config mirrors that of @rerorr19 (including redis). Another potential data point: only users sending requests from mobile safari web client have been affected. There have been no issues with those using desktop browsers.

> We don't suspect that it's a defect in session necessarily, but I was asked to inquire about any known session issues related to having the SPA and API on different subdomains. So far we could only reproduce the issue in our AWS environment with the two subdomains and are not sure why users would sporadically end up in each other's sessions. I know it's not much to work with.

**Comment by dougwilson** [comment] 2022-02-07 03:18
This issue has been open for some time and no further information from the OP in order for us to reproduce the issue, so closing for now.

**Closed by dougwilson** 2022-02-07 03:18 UTC
Labels: awaiting more info
