### ISSUE TITLE
session does not save after fetch post request with express

### ISSUE THREAD

**Issue by super2457** [expressjs/session#279] opened 2016-02-25 12:08 UTC
http://stackoverflow.com/questions/35612226/session-does-not-save-after-fetch-post-request-with-express

**Comment by JoeWagner** [comment] 2016-02-25 20:36
Hi @super2457 
I'm gonna close this since you mention in the SO question that you think its an issue with the client.  Feel free to re-open this issue if you find a problem with this module

**Closed by JoeWagner** 2016-02-25 20:36 UTC
Labels: question

**Comment by dougwilson** [comment] 2016-02-25 23:50
Yea, looking around, it is probably that the client is not sending the cookies. It looks like browser support is very low and most people are using a polyfill https://github.com/github/fetch and this library calls out specifically it will never send cookies (https://github.com/github/fetch#caveats):

> By default,  fetch  won't send any cookies to the server, resulting in unauthenticated requests if the site relies on maintaining a user session.

This module relies completely on cookies, so if that is the client @super2457 is using, then it will never work with this module due to that limitation.

**Comment by nodejh** [comment] 2016-09-11 20:04
`Fetch` does not send cookies. So you should add `credentials: 'include'` as fetch's parameter, look like this: 

```
fetch(URL_LOGIN, {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        username: 'username,
        password: 'password'
      })
    })
    .then((response) => response.json())
    .then((responseJson) => {
      console.log('fetch responseJson: ', responseJson);
    })
    .catch((error) => {
      console.error(error);
    });
```

**Comment by henriklundgren** [comment] 2016-12-03 09:15
@dougwilson Could we add this to the documentation, i.e. `credentials: 'include'`? Especially since Fetch will eventually be the default.

**Comment by gabeio** [comment] 2016-12-03 18:52
I think including other library's documentation into our documentation might end up being much more confusing to those who are *not* using the fetch library.

**Comment by henriklundgren** [comment] 2016-12-04 05:12
Agree,
but,
kind of dismissing Fetch as just another userland library
would be contrary to my point.

I would say though,
despite me not having any turtles in the race anymore,
this situation puzzled me for some odd hours, 
and when I finally solved it,
I kind of “blamed” express-session for not having any notes on this,
more then the whatwg or w3 orgs,
if you get my point.

**Comment by dougwilson** [comment] 2016-12-04 05:39
The problem is, there are so, so many different ways to make requests to the server. We also don't document how to use the cookie jar with cURL, as another example. At some point, we have to expect that users understand the library / program they are using to make the requests in the first place.
