### ISSUE TITLE
express session is not stroing data when redirecting the route.

### ISSUE THREAD

**Issue by umakanth-pendyala** [expressjs/session#790] opened 2020-10-24 10:10 UTC
Guys, I am using the express-session module to send data between 2 routes.

So here is the scenario.
When a user creates his account on the sign-up page, he will be redirected to the home page but I should display the users 'username' on the home page saying that "welcome <username>".

For this purpose, I used express-session but for some reason when I do `res.redirect('/)` the session data is not stored. 

Here is my server.js file.

```
const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const mongoose = require("mongoose");
const session = require("express-session");

mongoose.connect(
  "mongodb://localhost:27017/ONLINE_SHOPPING",
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  },
  err => {
    if (!err) console.log("successfull");
    else console.log("failed");
  }
);

//middle wares
app.use(express.static("public"));
app.use(
  bodyParser.urlencoded({
    extended: true,
  })
);
app.set("view engine", "ejs");
app.use(
  session({
    secret: "some-random-secret-key",
    resave: false,
    saveUninitialized: false,
  })
);

require("./app/routes")(app);

app.listen(3000, () => console.log("app is running on port 3000"));
```

Here is the post route for the sign_up form.
```
router.post("/sign_up", async (req, res) => {
  const User = mongoose.model("user", userSchema);
  req.body.homeAddress = "new nullakunta";
  try {
    const user = new User({
      name: req.body.username.trim(),
      email: req.body.email.trim(),
      password: req.body.password.trim(),
      homeAddress: req.body.homeAddress,
    });
    const result = await user.save();
    if (result != null || result != undefined) {

      req.session.username = result.username;
      req.session.cookie.expires = false;
      req.session.save(err => {
        if (err) res.send("error occured while saving the session.");
        res.redirect("/");
      });
      return;

    } else {
      res.send("account not created");
      return;
    }
  } catch (e) {
    res.send("account not created");
    return;
  }
});
```
i am storing the username like this `req.session.username = result.username; ` if u see in the above code. 

Here is my home page(get) route.
```
router.get("/", (req, res) => {
  if (req.session.username != null || req.session.username != undefined) {
    console.log('user name is', req.username);
  }
  console.log(req.session);
  res.render("catalog");
});
```

Every time I run the server and signs up the control never goes into the if loop mentioned in the home`('/')` route
the output of the following statement ` console.log(req.session);` in home route is 

```
Session {
  cookie: { path: '/', _expires: null, originalMaxAge: null, httpOnly: true }
}
Session {
  cookie: { path: '/', _expires: null, originalMaxAge: null, httpOnly: true }
}
```

Can someone help what the problem is? And how to solve it?

**Comment by dougwilson** [comment] 2020-10-25 05:06
Hi @umakanth-pendyala there isn't enough provided above to reproduce the issue, but it seems like you likely just need to ensure that the session is committed to your store using `req.session.save` before calling the redirect, as that has resolved the issues for some folks in the past. If you have not tried that, I would at least suggest testing out if that resolves it, otherwise, please provide a complete app and the steps we need to do to see the issue, thank you!

**Comment by umakanth-pendyala** [comment] 2020-10-25 05:19
Hey, Thanks for the reply. I did as you asked and called the redirect method in save callback. But unfortunately, that did not work.
Here. Take a look at the complete app here. 
https://github.com/umakanth-pendyala/ONLINE-SHOPPING.git.

Steps to encounter the problem.
Launch the server and try to sign up. You will understand the problem by then.

**Comment by umakanth-pendyala** [comment] 2020-10-25 14:32
@dougwilson Hey found any solution to the problem?

**Comment by frnk94** [comment] 2020-10-25 22:41
@umakanth-pendyala I ran your app and its working fine. After being redirected to `/` im logged in as the new user

**Comment by umakanth-pendyala** [comment] 2020-10-26 01:56
@frnk94 Wait, hold on. So you ran the code exactly. did not do any changes?

**Comment by umakanth-pendyala** [comment] 2020-10-26 02:05
Hey.I just realized that i added another `const session = require('express-session');` in my **sign_up js** file other than **server.js** file. I removed that extra statement and ran my code. And the data seems to be persistent. I guess the problem is solved now. Anyway thanks for the help guys.

**Comment by frnk94** [comment] 2020-10-26 15:15
@umakanth-pendyala you should close the issue :)

**Closed** 2020-10-26 15:42 UTC
Labels: awaiting more info

**Comment by khadeshyam** [comment] 2023-01-07 17:09
Even I got the same problem

**Comment by maestroh1git** [comment] 2023-06-14 13:33
me too,

I am adding an object to the session in a google OAuth callback, then redirecting to the "/" page.
but the request.session doesn't persist so I cant access the req.session.user object I added.

**Comment by DavidForDev** [comment] 2023-11-29 07:00
also, I have the same problem, anyone has any solutions?

**Comment by DiegoEsperidion** [comment] 2024-05-10 21:47
i have a similar problem but it occurs after logging in, the issue is that my app is of doing a motivation questoinary for school students. The thing is that a student does not have a password only a username, well the thing works well i can access to the portal and begin my questionary, well here it comes the problem sometimes when i finish the project there it comes the thing that my req.session(school and student) gets undefined but this is random,because sometimes works well, so i dont know how to make 100% effective, how can i do it?

**Comment by Loki-Afro** [comment] 2025-02-27 14:03
@DiegoEsperidion was your session itself undefined or school and student?

if the first is defined, you might have gotten a new session (for whatever reason) if the latter, try setting DEBUG=express-session  as an env var, maybe you get some more info

**Comment by bjohansebas** [comment] 2025-02-27 21:46
if you have issues, please open a new one instead of commenting on an old one.
