### ISSUE TITLE
isModified() always returns true even not modified

### ISSUE THREAD

**Issue by pamu777** [expressjs/session#829] opened 2021-06-02 19:10 UTC
hash function hashes 'req' property when checking modified or not.
so, "req" should be be ignored when hash. otherwise isModified always true due to req property from req.session.req

below is suggested code to fix this issue
```js
function hash(sess) {
  // serialize
  var str = JSON.stringify(sess, function (key, val) {
    // ignore sess.cookie property
    if (this === sess && (key === 'cookie' || key === 'req')) {
      return
    }

    return val
  })

  // hash
  return crypto
    .createHash('sha1')
    .update(str, 'utf8')
    .digest('hex')
}
```

**Comment by dougwilson** [comment] 2021-06-02 19:13
Hi @pamu777 can you please provide a reproducible test case so we can see this in action? The tests in the test suite test that when the session is not modified, it does not return that it is, so it would be interesting to see what would cause this. If you would like to make a PR that includes a test case that fails without the change and passes with the change, that would be great! If you're not sure how, we can help if you can provide a stand alone app that demonstrates the issue.

**Comment by pamu777** [comment] 2021-06-02 19:17
Oh. it reproduces every time with no modification on session.

**Comment by pamu777** [comment] 2021-06-02 19:18
code from description is suggested code to fix the issue.

**Comment by dougwilson** [comment] 2021-06-02 19:20
Hi @pamu777 I understand that, but I'm not able to reproduce the issue. We want to make sure that this does indeed fix the issue, but need to be able to create a test case that shows it happening. Can you provide an app that demonstrates this?

**Comment by dougwilson** [comment] 2021-06-02 19:24
I created a simple app that shows the contents of `JSON.stringify(req.session)` from this module:
```js
const express = require('express')
const session = require('express-session')

const app = express()

app.use(session({ secret: 'keyboard cat' }))

app.get('/', (req, res) => {
  console.log('JSON.stringify(req.session) = ')
  console.log(JSON.stringify(req.session))
  res.end()
})

app.listen(3000)
```

The output I get is the following:
```
JSON.stringify(req.session) =
{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}}
```

Since I didn't add any properties to the request, it just has the `cookie` one there. We exclude that already in our hash part, though. There is no `req` property included. Perhaps can you add on to the app above to show where a `req` is appearing in the `JSON.stringify` output?

**Comment by pamu777** [comment] 2021-06-02 20:01
that is really weird. in your example below codes do nothing from session.js
but when I check from my app. session object has req and sessionID both
```
Object.defineProperty(this, 'req', { value: req });
Object.defineProperty(this, 'id', { value: req.sessionID });
```

session.js
```
function Session(req, data) {
  Object.defineProperty(this, 'req', { value: req });
  Object.defineProperty(this, 'id', { value: req.sessionID });

  if (typeof data === 'object' && data !== null) {
    // merge data into this, ignoring prototype properties
    for (var prop in data) {
      if (!(prop in this)) {
        this[prop] = data[prop]
      }
    }
  }
}
```

**Comment by dougwilson** [comment] 2021-06-02 20:06
Well, `JSON.stringify` automatically ignores non-enumerable properties, which both `req` and `id` are. The `cookie` would be one too if it were not for some historical reasons that can't be addressed with out a major revision.

**Comment by dougwilson** [comment] 2021-12-24 08:29
Closing due to no further response and no reproduction provided.

**Closed by dougwilson** 2021-12-24 08:29 UTC
Labels: awaiting more info
