### ISSUE TITLE
Compatibility issue for Chome and Safari

### ISSUE THREAD

**Issue by EthanGD** [expressjs/session#845] opened 2021-09-08 07:33 UTC
Dear All,

We found that,
under
    "express": "^4.17.1",
    "express-session": "^1.17.1",
and when we are using the configuration like
```
const sessionOption = {
  secret: 'secret',
  resave: false,
  store: new RedisStore({ client: redisClient }),
  saveUninitialized: true,
  //cookie: { maxAge: 3600000000 }
  //  cookie: { expires: new Date(253402300000000) },
  cookie: { expires: new Date(253402300000000),domain:"domain" },
  //cookie: { expires: new Date(253402300000000), secure: true },
  //cookie: { expires: new Date(253402300000000), secure: false },
  //  cookie: { maxAge: 3600000000,secure: true, sameSite: 'lax', httpOnly: true },
};
```
and when we request by Chome 67 / Safari 11 or the version before,
the cookies could not  be saved successfully.

How can I resolve this problem?
Thank you so much.

Best Regards,
Ethan

**Comment by NG235** [comment] 2021-09-24 08:08
Can you try with a different expiry. It could be that it is too far into the future.

**Comment by dougwilson** [comment] 2021-11-16 19:04
Hi @EthanGD sorry I am not able to reproduce the issue on either of those web browsers with any of the configurations you provided. Is it possible you can can provide full code that I can run locally which demonstrates the issue? Another alternative is that we always accept pull requests for fixes that you diagnose as well.

**Comment by dougwilson** [comment] 2021-12-24 08:27
Closing due to no further response.

**Closed by dougwilson** 2021-12-24 08:27 UTC
Labels: awaiting more info
