### ISSUE TITLE
session cookie not saving

### ISSUE THREAD

**Issue by sethdorris** [expressjs/session#512] opened 2017-09-27 20:52 UTC
In the login endpoint the req.session.userId is being set and I can see the userId when I log it to the console inside the endpoint

```
Sesson Data Session {
  cookie:
   { path: '/',
     _expires: 2017-10-27T20:47:19.941Z,
     originalMaxAge: 2592000000,
     httpOnly: true,
     secure: false },
  userId: 17 }
```

Problem is when the user clicks refresh button and my application calls /loginrefresh  ... no cookie-headers are present on the request and no cookie is in the local cookie storage... wtf?

```js 
var express = require("express");
var Knex = require("knex");
var pg = require("pg");
var path = require("path");
var pool = require("./db");
var bodyParser = require("body-parser");
var http = require("http")
var fs = require("fs");
var scrypt = require("scrypt-for-humans");
var Promise = require("bluebird");
var config = require("./session-config");
var session = require ("express-session");
var KnexSessionStore = require("connect-session-knex")(session);
var app = express();
var api  = require('./api');
var MyTeamVMCreator = require('./ViewModelCreators/MyTeamViewModelCreator');
var StatTrackerVMCreator = require('./ViewModelCreators/StatTrackerVMCreator');
var fetch = require('node-fetch');
var theServer = http.createServer(app);
var expressWs = require('express-ws')(app, theServer);
var mockAPI = require('./MockAPI');
var wss = expressWs.getWss('/tracker');

var store = new KnexSessionStore({
  knex: knex
})

app.use(session({
  store: store,
  secret: config.sessions.secret,
  cookie: { maxAge: 30 * 24 * 60 * 60 * 1000, secure: false },
  resave: false,
  saveUninitialized: false,
}))
app.use(bodyParser.json());
app.use("/build", express.static(path.join(__dirname, "..", "build")));

app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname, "..", "index.html"))
})

app.post('/register', function (req, res) {
  return Promise.try(() => {
    return UserAlreadyExists(req.body.email, req.body.username)
  }).then(exists => {
    console.log("exists",exists);
    if (!exists) {
      console.log("inside exists if")
      Promise.try(() => {
        return scrypt.hash(req.body.password);
      }).then(hash => {
         return knex("users")
        .returning('id')
        .insert({
          username: req.body.username,
          password: hash,
          email: req.body.email
        });
        console.log("INSERT COMPLETE", userId)
      }).then(row => {
        console.log("row", row)
        req.session.userId = row;
        res.json({ username: req.body.username, userId: row});
      }).catch(err => {
        res.send(err);
      })
    } else {
      res.json(exists);
    }
  })
});

app.get('/loginrefresh', function (req, res) {
  console.log(req.session)
  console.log(req.session.userId);
  var isUndefined = typeof req.session.userId == 'undefined';
  console.log("is userId undefined", isUndefined)
  if (typeof req.session.userId == 'undefined') {
    return res.sendStatus(200);
  }
  pool.query('SELECT * FROM users WHERE id = $1', [parseInt(req.session.userId)]).then(users => {
    console.log("why is this hit?")
    console.log("users", users)
    if (users.length === 0) {
      return res.send("User was not found.");
    } else {
      var userData = {
        username: users.rows[0].username,
        userId: users.rows[0].id
      }
      GetMostRecentTeam(users.rows[0].id)
      .then(function (data) {
        userData.recentteam = data.rows;
        console.log("data rows")
        return res.json(userData);
      })
    }
  })
})

app.post('/login', function (req, res) {
  let user;
    pool.query('SELECT * FROM users WHERE LOWER(username) = LOWER($1)', [req.body.username]).then( (users) => {
      if (users.length === 0) {
        res.send("User does not exist")
      } else {
        user = users.rows[0];
        console.log("USER DATA", user)
        return Promise.try(() => {
          return scrypt.verifyHash(req.body.password, user.password);
        }).then(() => {
          return GetMostRecentTeam(user.id).then(data => {
            req.session.userId = user.id;
            console.log("User Id", req.session.userId)
            console.log("Sesson Data", req.session)
            if (data.rows.length == 0) {
              return res.json({ username: user.username, userId: user.Id, recentteam: []})
            }
            console.log("Get most recent team", data)
            return res.json( {username: user.username, userId: user.Id, recentteam: data.rows })
          }).catch(e => {
            console.log("error", e)
          })
        }).catch(scrypt.PasswordError, (err) => {
          res.status(401).send("User password did not match");
        }).catch((err) => {
          res.status(500).send("An error occured with the authentication server.");
        })
      }
    })
  });

  app.get('/logout', function (req, res) {
    req.session.destroy();
    res.sendStatus(200);
  })

theServer.listen(process.env.PORT || 3000);
```

**Comment by Emad-salah** [comment] 2017-10-04 15:57
I'm experiencing that as well

**Comment by gabeio** [comment] 2017-10-05 16:28
Would you happen to be using any ajax calls to log the user in?

**Comment by Emad-salah** [comment] 2017-10-06 02:47
Sorry, I've just found out that I forgot to add withCredentials in the header of my Ajax call. anyone who stumbles upon this issue, should double check if they're including that already or not :)

**Comment by gabeio** [comment] 2017-10-06 02:56
@dougwilson the issue over `withCredentials` seems to be cropping up a lot more it *may* be worth our while to add an issue template suggesting that if their issue is that the cookies are not showing up / sessions don't seem be applying to the browser to please try adding `withCredentials` if they are doing any type of ajax/xhr requests.

**Comment by dougwilson** [comment] 2017-10-06 03:02
Or just something in the readme somewhere. Probably a section for how sessions work (i.e. stores data on server and id in browser cookie) and in there, some kind of note. I asdumd the uptick is from folks doing cross origin, not AJAX itself. Just setting withCredentials alone won't fix it without also having CORS with the proper settings on the remote server as well.

**Comment by azarus** [comment] 2017-10-16 20:40
Another problem here is that:
```
  res.setHeader('set-cookie', header)
```

`set-cookie` is lowercase and some browsers are sensitive to that

`Set-Cookie` is the prefered method to set the cookies

**Comment by gabeio** [comment] 2017-10-17 03:17
https://www.w3.org/Protocols/rfc2616/rfc2616.txt

> Each header field consists of a name followed by a colon (":") and the field value. Field names
   are case-insensitive.

**Comment by azarus** [comment] 2017-10-17 04:20
@gabeio Internet Explorer!

**Comment by dougwilson** [comment] 2017-10-17 04:26
I use this module every day with IE 6, 7, 9, 9, 10, 11 an the new Edge versions as well with no issues. If you are having an issue, please open a new issue, detailing all the steps to reproduce including exact version of this module, of Node.js, of Internet Explorer, and complete source code and instructions to reproduce.

**Closed** 2017-10-17 04:27 UTC
Labels: awaiting more info
