### ISSUE TITLE
Incorrect session state?

### ISSUE THREAD

**Issue by pwdonald** [expressjs/session#211] opened 2015-09-16 15:59 UTC
Node: 0.12.6

I have noticed that when using `express-session` with `passport`, after login or when a flash message is appended the session data is not updated until a second request is made (like a refresh of the login page) when hosting from a Windows machine. 

This behavior does not seem to be reproducible on a Linux host.

This results in the flash error message or login state not being updated until a subsequent request is made.

```js
app.use(express.static(path.join(__dirname, 'public')));
app.use(cookieParser('secret'));
app.use(session({
    secret: 'secret',
    name: 'sessionname',
    cookie: {
        maxAge: 365 * 24 * 3600 * 1000 // One year for example
    },
    store: new NedbStore({
        filename: 'data/sessions'
    }),
    resave: false,
    saveUninitialized: true
}));
app.use(flash());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: false
}));

app.use(passport.initialize());
app.use(passport.session());
```

**Comment by dougwilson** [comment] 2015-10-25 21:42
Weird. Can you provide a complete `app.js` file that we can run and then provide the steps to reproduce?

**Comment by dougwilson** [comment] 2015-12-15 05:06
Hi! I'm closing this issue because I never got the example application I asked for to diagnose further. If you prove the example, I can always re-open and investigate further :)

**Closed by dougwilson** 2015-12-15 05:06 UTC
Labels: question
