### ISSUE TITLE
Parse session from websockets request

### ISSUE THREAD

**Issue by rafaelsales** [expressjs/session#592] opened 2018-06-09 18:16 UTC
Is this supposed to be supported by the session lib?

The websockets request comes with headers which the cookie, so I couldn't picture a reason why the lib doesn't parse and includes the session into the req object.

**Comment by dougwilson** [comment] 2018-06-09 18:19
I've never tested it. I suppose it may work. Does it work? If not, what changes would be required to make it work? This is no different than any Express middleware so it should work on any requests going through Express middleware.

**Comment by rafaelsales** [comment] 2018-06-09 19:26
@dougwilson thanks for the quick response. Yeah, I've read most of the session lib source and couldn't see a reason for it not work.

I found a way, by manually calling session on the express websockets upgrade request handler:

```js
import Express from 'express'
import ExpressSession from 'express-session'
import proxy from 'http-proxy-middleware'

const session = ExpressSession({ ... })

const websocketsProxy = proxy('/websockets', {
  target: CONFIG.backendServerURL,
  changeOrigin: true,
  ws: true,
  onProxyReqWs: (proxyReq, req, socket) => {
    proxyReq.setHeader('Authorization', `Bearer ${req.session.accessToken}`)
  },
})

const app = Express()
app.use(session) // Handles creating/reading session in normal HTTP requests

const server app.listen(PORT)

server.on('upgrade', (req, socket) => {
  // The only thing I dislike is passing the empty `{}` object as a fake `response`
  // object, which the session object shouldn't need here
  session(req, {}, () => {
    // Calls proxy when req.session is already present
    websocketsProxy.upgrade(req, socket)
  })
})
```

Can you think of way of doing this that looks less hacky?

Thanks!

**Comment by dougwilson** [comment] 2018-06-09 19:30
So from the code it looks like the WebSocket request is not going through all the normal Express middleware, is that right? Sorry I just have never actually used WebSockets at all so not super familiar with how specifically work in Node.js. Is there some method in which you can "mount" Express.js middleware onto WebSocket requests? If so, that would likely be the method to make it look less hacky.

**Comment by dougwilson** [comment] 2018-06-09 19:31
I typed "express middleware websocket" in to Google and the first result was https://www.npmjs.com/package/express-ws . It looks like that would solve your issue. Does that module work?

**Comment by rafaelsales** [comment] 2018-06-09 19:34
With pure express, I believe the 'upgrade' handler is the only way to do it, and it's understandable because there's just no `response` object that would make sense for a middleware.

I found an example of doing the same hack I'm doing here: https://github.com/websockets/ws/blob/master/examples/express-session-parse/index.js#L53-L54

It's just a bit different because I don't actually have a websockets server in my node server - I just create a proxy to inject auth token and let the connection be established with my other backend server that is not in node.

**Comment by dougwilson** [comment] 2018-07-06 03:55
Ok. So I'm trying to figure out if that was an answer to my yes / no question. Do you still need help? I'm not sure how to really help, though. Any thoughts on what I can do?

**Comment by hei-pa** [comment] 2018-07-17 17:57
I have the same problem using `express-ws` and `express-session`.

`express-session` does not set a new session cookie

**Comment by dougwilson** [comment] 2018-07-17 18:19
Can you provide code and steps so I can reproduce the issue to debug it?

**Comment by dougwilson** [comment] 2018-11-04 01:12
I'm going to close this for now since I never heard back and not sure how to proceed.

**Closed by dougwilson** 2018-11-04 01:12 UTC
Labels: awaiting more info
