### ISSUE TITLE
session doesn't save

### ISSUE THREAD

**Issue by neutron92** [expressjs/session#371] opened 2016-10-14 17:21 UTC
``` js
app.use(cookieParser());
app.use(session({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: true,
    cookie: {
        secure: false
    }
}))
```

``` js
app.post('/login', (req, res) => {
    let user = Users.findOne({
        username: req.body.username,
        password: req.body.password
    }, function(err, doc) {
        console.log(err, doc);
        if (doc && doc._id) {
//here changing of the session
            req.session.user = doc;
            req.session.save((err) => {
                if (!err) {
                    console.log(req.session);
                    res.redirect("/");
                }
            });
        }
    });
    //console.log(req.session);
});
```

``` js
app.use(function(req, res, next) {
    console.log(req.session);//here it logs the session without the user
    if (req.path === "/login" || req.path === "/register" || req.path === "/registerUser" || req.path === "/instagram/registerUser" || (req.session && req.session.user)) {
        next();
    } else {
        res.redirect("/login");
    }
});
```

**Comment by gabeio** [comment] 2016-10-14 17:30
it has to do with a bug you have to `session.save()` before you redirect.

**Comment by hich-em** [comment] 2016-10-14 17:32
i did it 

```
req.session.save((err) => {
                if (!err) {
                    console.log(req.session);
                    res.redirect("/");
                }
            });
```

**Comment by gabeio** [comment] 2016-10-14 17:37
see #360.

**Comment by dougwilson** [comment] 2016-10-14 17:41
Hi @hich-em if you have that save in there it _should) work, but I hear you';re saying it doesn't. We would love to dig into your issue, but there is not enough information provided for us to do so. Can you please provide us with all the following information?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Full, complete source code for an app we can run to reproduce your issue. What you gave above is a good start, but it 3 snippets. We need the complete app we can simply copy and paste and run.
4. Describe the steps we need to perform on your app in order to reproduce the problem. Please include a description of what we'll see when the issue occurs.

Thanks!

**Comment by hich-em** [comment] 2016-10-14 17:44
i tried all sol°s there but no result

**Comment by hich-em** [comment] 2016-10-14 17:52
@dougwilson 
1) node version : 4.5.0
2) Express session plugin version: 1.14.1
3) for the code i can't give u whole the app because it is work app, i gave you the most important part where i used the session

Thanks!

**Comment by hich-em** [comment] 2016-10-14 17:53
@gabeio i tried it but no news

**Comment by dougwilson** [comment] 2016-10-14 18:12
Hi @hich-em it doesn't have to be _the_ app, but it does need to be _an_ app. As in, please take your snippet above, fill in all the missing variables such that it is actually a complete app. Because you still need to provide me the information in step 4, otherwise, I don't even know how to reproduce your issue. I tried to piece your snippets together myself and found no issues, so I have no reproduction case with the current information, so I don't know what else I can do.

**Comment by gabeio** [comment] 2016-10-20 03:32
@hich-em do you have any runnable app which can reproduce the issues you are having (preferably as small as possible)... as @dougwilson mentioned it's impossible for us at this moment to reproduce your issue without a fully functioning app. As many different things might be causing it even some middleware your company might have custom built but didn't realize "this" or "that" affected the session. Or even the session-store you are using. A lot of these are really needed to debug further.

**Comment by nilaysaha** [comment] 2016-10-21 10:36
Have the same problem. The example given in the github documentation even does not work. Every time in a running server, the number of views is always 1. I plugged in the error handling of @hich-em.  And here is the output:
`{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  views: { '/foo': 1 } }
views not found
{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  views: { '/foo': 1 } }
views not found
{ cookie: 
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  views: { '/foo': 1 } }`

So for each subsequent get request ...the number remains as 1. Is this the expected behaviour ?

**Comment by dougwilson** [comment] 2016-12-09 03:45
I'm going to close this since no app was never provided to look into anything.

**Closed by dougwilson** 2016-12-09 03:45 UTC

**Comment by andy-ata** [comment] 2018-04-01 23:44
I was having same issue, but I found a way around it. After ecery change to the session data, just do a req.session.save and u are good to go.

So something like this would do...

if(req.session.views){
    req.session.views++;
    req.session.save(callbackFunction);
}

Hope this helps

**Comment by mmayorivera** [comment] 2018-07-29 17:44
Does not work either...

**Comment by VitaliiLynnyk** [comment] 2019-01-18 14:19
+1 does not work.

**Comment by cizz3007** [comment] 2019-01-29 17:06
+1 sometimes work, sometimes doesnt work.
  Whyyyy?????

**Comment by vilmes21** [comment] 2019-11-17 09:03
I changed commented out this part and it starts working:
`    cookie: {
        // secure: true
    },`

**Comment by veushur** [comment] 2019-12-17 19:20
> I commented out this part and it starts working:
> ` cookie: { // secure: true },`

Works, but how do we make it secure now

**Comment by vilmes21** [comment] 2019-12-18 10:14
> > I commented out this part and it starts working:
> > ` cookie: { // secure: true },`
> 
> Works, but how do we make it secure now

See https://stackoverflow.com/a/40324493/8403046

**Comment by joshlsullivan** [comment] 2020-03-28 19:30
When I commented out `secure: true`, it worked for me as well.

**Comment by faspadaro** [comment] 2020-05-21 13:45
It doesn't work for me.
In login It save user in session but in get request the req.session.user is undefined.
After "req.session.user = data" you note that "req.session.save( (err) => { req is undefined })"

```
app.use(cors({origin: [
  "http://localhost:4200"
], credentials: true}));

app.use(session({
    secret: 'secret',
    resave: false,
    saveUninitialized: true,
    cookie: { }
}))

const authMiddleware = (req, res, next) => {
  // req.session.user is undefined !
  if(req.session && req.session.user) {
    next();
  } else {
    res.status(403).send({
      errorMessage: 'You must be logged in.'
    });
  }
};

app.get("/get/contacts",  authMiddleware,(req, res) => {
  // ... other code
});




app.post('/api/login', validatePayloadMiddleware, (req, res) => {

  if (req.body.username === "XXXXXXXX" && req.body.password === "YYYYYYYYYYY")
  {
    req.session.user = {"user" : req.body.username};
    req.session.save((err) => {
       // err = undefined !
       console.log(err) 
    });
    let body = {
      id: 1,
      username: req.body.username,
      firstName: "FFFFF",
      lastName: "SSSSS",
      token: 'fake-jwt-token'
    };
    return res.status(200).json(body);
  }
  else
  {
    let body = {
          error: true,
          errorMessage: 'Permission denied!'
    };
    return res.status(403).json(body);
  }
});
```

**Comment by Hyzyr** [comment] 2022-01-14 19:00
same not works
