### ISSUE TITLE
Why does express session gets destroyed after every Ajax request?

### ISSUE THREAD

**Issue by ellensan** [expressjs/session#475] opened 2017-06-25 11:45 UTC
I'm trying to use express-session but it is not working the way I want. For example, if I visit http://127.0.0.1:8081/test from browser 3 times, I see following response in browser:

**Not set**

**Already set**

**Already set**

The means seesionID for is unique and session is not destroyed when I visit this page again and again.

However, the scenario changes when I request the same page using Ajax, which I have wrote in test.php file:

**test.php**

    <script type="text/javascript">
      $(document).ready(function(){
        setInterval(function(){
        $.ajax({
          type: 'get',
          url: 'http://127.0.0.1:8081/test',
          success: function(data){
            console.log(data);
          },
          error: function(aa, bb, cc){
                      // console.log("Ajax error", aa, bb, cc);
          	}
          });
         }, 5000);
      });
    </script>

**Server side code:**

    var express = require('express');
    var mysql = require('mysql');
    var session = require('express-session');
    // var MySQLStore = require('express-mysql-session')(session);
    var app = express();
    var bodyParser = require('body-parser');
    app.use(bodyParser.json({type: '*/*'}));
    var http = require('http');
    app.use(function (req, res, next) {
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
        res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
        next();
    });
    
    var server=http.createServer(app);
    
    app.use(session({
      secret: 'some secret',
      resave: false,
      // rolling: true,
      saveUninitialized: true,
      cookie: {
        secure: false,
        maxAge: 36000000,
        httpOnly: false,
      },
    }));
    
    
    app.get("/test", function(req, res, next){
         console.log(req.session);
      console.log(req.sessionID, req.session.name);
        if(!req.session.name){
            console.log("Not set.");
            res.write("Not set");
            req.session.name = "vikas kumar";
        } else {
            console.log("Already set");
            res.write("Already set");
            console.log(req.session.name);
        }
        res.end();
    });
    
    server.listen(8081, function(){
        var host = server.address().address;
        var port = server.address().port;
        console.log("testApp socket server is listening at http://%s:%s", host, port+"\n\n");
    });

From this, I see following response in browser's console:

**Not set**

**Not set**
**Not set** ... And so on.

Note: I'm not using default Memory Store for session.

Am I doing something wrong? Or it has something to do with Ajax request?

**Comment by dougwilson** [comment] 2017-06-26 03:45
Hi @ellensan thanks for the code. I'm not sure, but I think it's an issue with your client-side AJAX requests. Are the requests sending the session cookie with them? If not, it would result in the exact behavior you're describing, because if there is no cookie, the library doesn't have the session ID to load so automatically creates a new cookie.

**Comment by ellensan** [comment] 2017-06-27 11:59
@dougwilson one thing I want to know is about cross domain request. My home page in browser is http://127.0.0.1/test/index.php, from where I make above Ajax request. The URL in Ajax uses a PORT. So the difference in URIs is the PORT. Does it make them cross domains?

**Comment by btd** [comment] 2017-06-29 08:07
@ellensan yes, you need to set xhr property `xhr.withCredentials = true`. Or if you are using `fetch` add option: `{ credentials: 'include' }`

**Comment by dougwilson** [comment] 2017-07-04 04:19
@vikaskumar2299 said this is a duplicate of #474

**Closed by dougwilson** 2017-07-04 04:19 UTC
