### ISSUE TITLE
Store error handling always result to Cannot send headers...

### ISSUE THREAD

**Issue by semoro** [expressjs/session#225] opened 2015-11-08 14:42 UTC
When error thrown here
index.js:285
```javascript
req.session.save(function onsave(err) {
  if (err) {
    defer(next, err);
  }
  writeend();
});
```

It result in silent log message about that headers already send, because when `next(err)` via defer called it already `writeend();`

Example error log..
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/-/node_modules/express/lib/response.js:718:10)
    at ServerResponse.contentType (/-/node_modules/express/lib/response.js:551:15)
    at ServerResponse.send (/-/node_modules/express/lib/response.js:138:14)
    at ServerResponse.res.send (/-/node_modules/express-promise/lib/express_promise.js:204:13)
    at done (/-/node_modules/express/lib/response.js:957:10)
    at Object.exports.renderFile (/-/node_modules/jade/lib/index.js:374:12)
    at View.exports.__express [as engine] (/-/node_modules/jade/lib/index.js:417:11)
    at View.render (/-/node_modules/express/lib/view.js:126:8)
    at tryRender (/-/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/-/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/-/node_modules/express/lib/response.js:961:7)
    at /-/node_modules/express-promise/lib/express_promise.js:159:13
    at handleDone (/-/node_modules/express-promise/lib/express_promise.js:78:9)
    at resolveAsync (/-/node_modules/express-promise/lib/express_promise.js:67:12)
    at /-/node_modules/express-promise/lib/express_promise.js:94:7
```
It contains nor info where real problem is, so it taken time to understand what is wrong.

Also it can be same problem in another error handlers

**Comment by dougwilson** [comment] 2015-11-11 02:22
Hi!  This would signal that there is a bug in one of your custom Express error handlers. Can you provide an example of one or an application I can run here that will reproduce the issue?

**Comment by dougwilson** [comment] 2015-12-15 05:04
Hi! I'm closing this issue because I never got the example application I asked for to diagnose further. If you prove the example, I can always re-open and investigate further :)

**Closed by dougwilson** 2015-12-15 05:04 UTC
Labels: question
