### ISSUE TITLE
duplicate connect.sid cookie set on browser

### ISSUE THREAD

**Issue by uptownhr** [expressjs/session#448] opened 2017-03-30 18:23 UTC
When I redeploy a clean instance of my app & session store, the connect.sid cookie is duplicated on the browser. I can see the old connect.sid and the new connect.sid and causes a session error. The session handler will attempt to read from the old session id and not find the user's session as it longer exists. 

How can I prevent express-session from creating another connect.sid if the user already has that cookie?

https://ipfs.io/ipfs/QmXCui5wd4fpTuYDaTZBwU18FTGv4FU4K8gUeiqtGqcGLx

**Comment by dougwilson** [comment] 2017-03-31 01:35
Hi @uptownhr that can happen if there is some parameter different between the two cookies (like domain, path, secure, etc.). The screenshot doesn't have enough information to tell. Can you provide the following information?

1. The version of this module
2. Complete code I can run and reproduce the issue with
3. Instructions for how to run the code and the steps to cause the issue

Thank you!

**Comment by dougwilson** [comment] 2017-04-21 17:06
Closing issue since I never heard anything back.

**Closed by dougwilson** 2017-04-21 17:06 UTC
Labels: awaiting more info

**Comment by ElChupacabra26** [comment] 2017-04-26 21:03
Is there a setting which avoids the cookie duplication or would it require manual deletion of the dupe? (i.e. in the case of different subdomains of the same domain)

**Comment by uptownhr** [comment] 2017-05-24 01:28
@dougwilson I will try and provide but can you please reopen this issue. 

@dougwilson I can't share my project, but I will try and set something up that reproduces this issue. 

I do believe the issue is related to multiple applications using the same session. For example, I have app.domain.com and www.domain.com that both relies on the same session.

**Comment by uptownhr** [comment] 2017-05-24 01:29
1. Version: express-session@^1.15.0

Step 2, 3 to come
