### ISSUE TITLE
Sessions getting mixed up

### ISSUE THREAD

**Issue by slpn1** [expressjs/session#555] opened 2018-02-16 16:50 UTC
Is it possible for sessions to get mixed up with other sessions. I'm quite certain my code is ok and there is nowhere where I am touching other uses sessions, yet very occasionally when I inspect a session object, I can see it has some variables that are set correct and some that are from another session object.

I have the app hosted on AWS EB, so it is behind a nginx server and wonder if that might be something to do with it?

I am using redis as a store like below:

```
let session = require('express-session');
let redisStore = require('connect-redis')(session);
let sessionMiddleware = session({
  secret: 'secrethere',
  resave: false,
  saveUninitialized: true,
  // eslint-disable-next-line new-cap
  store: new redisStore({client: redis}),
});

```
Thanks, Simon

**Comment by slpn1** [comment] 2018-02-16 17:06
Hi @dougwilson thanks for the quick response. I am happy to share my setup, I will need some time though as away for the weekend. This may be way off, but probably worth a look, do you think it could be related to something like mentioned in the comments [here](https://stackoverflow.com/questions/37791776/express-sessions-getting-mixed-up-for-some-users-with-passport-js)

**Comment by dougwilson** [comment] 2018-02-16 17:09
It's possible. Do you have something in front of Express that is caching responses and sharing the cache between users?

**Comment by slpn1** [comment] 2018-02-16 17:23
Thinking about it, I don't think this could be the issue as I have managed to reproduce it when running Node locally.  Unfortunately it happens very infrequently and I have yet to find a way to reproduce the issue repeatedly. I have some time on this, so will see what I can find! Thanks, Simon




________________________________

**Comment by dougwilson** [comment] 2018-03-09 13:26
I'm going to close this since there hasn't been an update in a while. If you have more information on how we can reproduce it to fix, or you know the code that needs to be fixed, I will definitely reopen!

**Closed by dougwilson** 2018-03-09 13:26 UTC
Labels: awaiting more info

**Comment by hsynlms** [comment] 2022-05-10 14:42
I also came up with this issue. In my case, it seems like it happens -infrequently- when the database load is high. The requested page is being loaded for 50+ seconds and sometimes I see another logged-in user session.
